settings: add required review concurrency to Copilot-CLI setting
The [review] concurrency field is required for Sashiko to work. The
documentation for Copilot-CLI provides a cp command to use the given
example as a template instead of the default configuration, but because
it does not have any concurrency field, the provided template will make
Sashiko fail with the following message:

Error: Failed to load settings from /home/<username>/.config/sashiko.toml

Caused by:
    missing configuration field "review"

For ease of use and compatibility with the current documentation,
inherit the concurrency field from the default configuration.

Signed-off-by: Javier Carrasco <javier.carrasco.cruz@gmail.com>